### ISSUE TITLE
Python models cannot be pickled

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1119]
If you try to pickle a Python model from an mlpack binding, it fails:

```
>>> o = logistic_regression(training=x, labels=y, lambda_=0.5)
[WARN ] --output_file ignored because --test_file is not specified.
[WARN ] --output_probabilities_file ignored because --test_file is not specified.
>>> import pickle
>>> pickle.dump(o['output_model'], open('model.pkl', 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle LogisticRegressionType objects
```

I think just the `__getstate__()` and `__setstate__()` functions need to be added to the mlpack model types.

**Comment by rcurtin** [comment]
Fixed in #1125.
