### ISSUE TITLE
Python bindings fail to build: AttributeError: module 'pythran' has no attribute '__version__'

### ISSUE THREAD

**Issue by yurivict** [mlpack/mlpack#3456]
#### Issue description
```
[  9% 31/258] cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=approx_kfn.pyx
FAILED: src/mlpack/methods/CMakeFiles/build_pyx_approx_kfn /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/methods/CMakeFiles/build_pyx_approx_kfn 
cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=approx_kfn.pyx
running build_ext
cythoning mlpack/approx_kfn.pyx to mlpack/approx_kfn.cpp
Traceback (most recent call last):
  File "/usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py", line 119, in <module>
    setup(name='mlpack',
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    result = cython_compile(source, options=options,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 786, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 731, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 479, in run_pipeline
    context = options.create_context()
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 600, in create_context
    return Context(self.include_path, self.compiler_directives,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 80, in __init__
    from . import Builtin, CythonScope
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 16, in init Cython.Compiler.Visitor
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 31, in <module>
    from .Pythran import has_np_pythran, pythran_type, is_pythran_buffer
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Pythran.py", line 11, in <module>
    pythran_is_pre_0_9 = tuple(map(int, pythran.__version__.split('.')[0:2])) < (0, 9)
AttributeError: module 'pythran' has no attribute '__version__'
[ 10% 31/258] cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=bayesian_linear_regression.pyx
FAILED: src/mlpack/methods/CMakeFiles/build_pyx_bayesian_linear_regression /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/methods/CMakeFiles/build_pyx_bayesian_linear_regression 
cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=bayesian_linear_regression.pyx
running build_ext
cythoning mlpack/bayesian_linear_regression.pyx to mlpack/bayesian_linear_regression.cpp
Traceback (most recent call last):
  File "/usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py", line 119, in <module>
    setup(name='mlpack',
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    result = cython_compile(source, options=options,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 786, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 731, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 479, in run_pipeline
    context = options.create_context()
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 600, in create_context
    return Context(self.include_path, self.compiler_directives,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 80, in __init__
    from . import Builtin, CythonScope
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 16, in init Cython.Compiler.Visitor
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 31, in <module>
    from .Pythran import has_np_pythran, pythran_type, is_pythran_buffer
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Pythran.py", line 11, in <module>
    pythran_is_pre_0_9 = tuple(map(int, pythran.__version__.split('.')[0:2])) < (0, 9)
AttributeError: module 'pythran' has no attribute '__version__'
[ 10% 31/258] cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=decision_tree.pyx
FAILED: src/mlpack/methods/CMakeFiles/build_pyx_decision_tree /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/methods/CMakeFiles/build_pyx_decision_tree 
cd /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python && /usr/local/bin/python3.9 /usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py build_ext --module=decision_tree.pyx
running build_ext
cythoning mlpack/decision_tree.pyx to mlpack/decision_tree.cpp
Traceback (most recent call last):
  File "/usr/ports/misc/py-mlpack/work-py39/.build/src/mlpack/bindings/python/setup.py", line 119, in <module>
    setup(name='mlpack',
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    result = cython_compile(source, options=options,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 786, in compile
    return compile_single(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 731, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 479, in run_pipeline
    context = options.create_context()
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 600, in create_context
    return Context(self.include_path, self.compiler_directives,
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 80, in __init__
    from . import Builtin, CythonScope
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 16, in init Cython.Compiler.Visitor
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 31, in <module>
    from .Pythran import has_np_pythran, pythran_type, is_pythran_buffer
  File "/usr/local/lib/python3.9/site-packages/Cython/Compiler/Pythran.py", line 11, in <module>
    pythran_is_pre_0_9 = tuple(map(int, pythran.__version__.split('.')[0:2])) < (0, 9)
AttributeError: module 'pythran' has no attribute '__version__'
^Cninja: build stopped: interrupted by user.
```
#### Your environment

 * version of mlpack: 4.0.1
 * operating system: FreeBSD 13.1
 * compiler: clang-14
 * version of dependencies (Boost/Armadillo): boost-libs-1.81.0 armadillo-12.0.1

**Comment by rcurtin** [comment]
That looks Cython-internal to me; maybe report this there?  I don't think any mlpack code is the source of the bug here.

**Comment by yurivict** [comment]
It turned out that pythran was too old.

Thanks.
