### ISSUE TITLE
[Python API] Binary Incompatibility

### ISSUE THREAD

**Issue by rootjalex** [mlpack/mlpack#3772]
#### Issue description

I ran `pip import mlpack`, and when running `import mlpack`, see the following error:
```pycon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dir/venv/lib/python3.12/site-packages/mlpack/__init__.py", line 13, in <module>
    from .approx_kfn import approx_kfn
  File "mlpack/approx_kfn.pyx", line 1, in init mlpack.approx_kfn
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

#### Your environment

 * version of mlpack: 4.3.0
 * operating system: MacOS
 * compiler: Apple clang version 15.0.0
 * version of dependencies (Boost/Armadillo): Not sure
 * any other environment information you think is relevant:

#### Steps to reproduce

```bash
(venv) ajroot dir % pip install mlpack
Collecting mlpack
...
Successfully installed cython-3.0.10 mlpack-4.3.0.post2
(venv) ajroot dir % python3
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dir/venv/lib/python3.12/site-packages/mlpack/__init__.py", line 13, in <module>
    from .approx_kfn import approx_kfn
  File "mlpack/approx_kfn.pyx", line 1, in init mlpack.approx_kfn
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

#### Expected behavior

The import should succeed.

#### Actual behavior

The import did not succeed.

**Comment by rcurtin** [comment]
Thanks for the clear report... I think this may be due to the numpy version 2 changes.  Can you check what the version of numpy you have installed is?  (e.g. check `numpy.__version__`)

**Comment by rootjalex** [comment]
Yep, I have numpy 2.0.1

**Comment by rcurtin** [comment]
Ok, I think the wheels on PyPI need to be rebuilt with the patches from #3752 then.  I just pushed an update to start those rebuilding again, but they take a while and I have been fighting project size limits on PyPI, so it could be a couple days before they all get uploaded.  I'll post another update when I see that the macOS wheels for Python 3.12 are successfully built and available. :+1:

**Comment by rcurtin** [comment]
Sorry I forgot to respond to this!  The updated version should be on PyPI now.  Let me know if there are any issues with it. :+1:
